from __future__ import annotations

from collections import Counter
from uuid import uuid4

from app.models import (
    DataSufficiencyLevel,
    EvaluationType,
    FactorCatalogSource,
    FactorEvaluationScope,
    FactorFormulaCatalogReport,
    FactorFormulaItem,
    FactorImplementationStatus,
    StrategyFamily,
)


def build_worldquant_style_factor_catalog() -> tuple[FactorFormulaCatalogReport, list[FactorFormulaItem]]:
    items = [_factor(**item) for item in _WORLDQUANT_STYLE_FACTORS]
    family_counts = Counter(item.factor_family for item in items)
    scope_counts = Counter(item.evaluation_scope.value for item in items)
    status_counts = Counter(item.implementation_status.value for item in items)
    data_level_counts = Counter(item.data_sufficiency_level.value for item in items)
    baseline_count = sum(1 for item in items if "baseline_candidate" in item.baseline_roles)
    report = FactorFormulaCatalogReport(
        report_id=f"worldquant_style_factor_catalog_{uuid4().hex[:8]}",
        source=FactorCatalogSource.WORLDQUANT_101_STYLE,
        total_items=len(items),
        family_counts=dict(sorted(family_counts.items())),
        scope_counts=dict(sorted(scope_counts.items())),
        implementation_status_counts=dict(sorted(status_counts.items())),
        data_level_counts=dict(sorted(data_level_counts.items())),
        baseline_candidate_count=baseline_count,
        factor_ids=[item.factor_id for item in items],
        findings=[
            f"Cataloged {len(items)} WorldQuant-style factor template(s).",
            f"{baseline_count} template(s) can become OHLCV baseline candidates.",
            "Cross-sectional templates require a multi-symbol universe before they are valid tests.",
            "These are formula archetypes, not copied Alpha101 implementations or validated alpha.",
        ],
    )
    return report, items


def _factor(**kwargs) -> FactorFormulaItem:
    return FactorFormulaItem(
        source=FactorCatalogSource.WORLDQUANT_101_STYLE,
        **kwargs,
    )


_COMMON_OVERFITTING_WARNINGS = [
    "Do not optimize the lookback window on the same sample used for final evaluation.",
    "Compare against simple momentum, reversal, and buy-and-hold baselines before treating this as alpha.",
]


_WORLDQUANT_STYLE_FACTORS = [
    {
        "factor_id": "wq_style_ts_momentum_20_60",
        "name": "Time-Series Momentum Rank",
        "description": "Ranks recent return strength through a longer rolling window.",
        "formula_expression": "ts_rank(close / delay(close, 20) - 1, 60)",
        "factor_family": "momentum",
        "strategy_family": StrategyFamily.CONTINUOUS_TREND_OR_MOMENTUM,
        "evaluation_scope": FactorEvaluationScope.SINGLE_ASSET_TIME_SERIES,
        "implementation_status": FactorImplementationStatus.PORTABLE_OHLCV,
        "required_fields": ["close"],
        "required_operators": ["delay", "ts_rank"],
        "lookback_windows": [20, 60],
        "baseline_roles": ["baseline_candidate", "momentum_baseline"],
        "crypto_compatibility_notes": ["Works as a single-symbol crypto baseline when evaluated as time-series momentum."],
        "overfitting_warnings": _COMMON_OVERFITTING_WARNINGS,
        "tags": ["ohlcv", "momentum", "time_series"],
    },
    {
        "factor_id": "wq_style_short_reversal_5_20",
        "name": "Short-Horizon Reversal Rank",
        "description": "Scores recent losers higher as a simple mean-reversion benchmark.",
        "formula_expression": "-ts_rank(close / delay(close, 5) - 1, 20)",
        "factor_family": "reversal",
        "strategy_family": StrategyFamily.VWAP_EXHAUSTION_REVERSION,
        "evaluation_scope": FactorEvaluationScope.SINGLE_ASSET_TIME_SERIES,
        "implementation_status": FactorImplementationStatus.PORTABLE_OHLCV,
        "required_fields": ["close"],
        "required_operators": ["delay", "ts_rank"],
        "lookback_windows": [5, 20],
        "baseline_roles": ["baseline_candidate", "mean_reversion_baseline"],
        "crypto_compatibility_notes": ["Useful as a sanity check for failed-breakout and exhaustion ideas."],
        "overfitting_warnings": _COMMON_OVERFITTING_WARNINGS,
        "tags": ["ohlcv", "reversal", "time_series"],
    },
    {
        "factor_id": "wq_style_volatility_compression_20_60",
        "name": "Volatility Compression",
        "description": "Ranks low realized volatility regimes as possible breakout or trend-preparation states.",
        "formula_expression": "-ts_rank(stddev(returns(close), 20), 60)",
        "factor_family": "volatility",
        "strategy_family": StrategyFamily.GENERAL_OR_UNKNOWN,
        "evaluation_scope": FactorEvaluationScope.SINGLE_ASSET_TIME_SERIES,
        "implementation_status": FactorImplementationStatus.PORTABLE_OHLCV,
        "required_fields": ["close"],
        "required_operators": ["returns", "stddev", "ts_rank"],
        "lookback_windows": [20, 60],
        "baseline_roles": ["baseline_candidate", "regime_feature"],
        "crypto_compatibility_notes": ["Should usually be a filter or setup score rather than a standalone entry rule."],
        "overfitting_warnings": ["Volatility filters can accidentally select quiet bull runs; evaluate by regime bucket."],
        "tags": ["ohlcv", "volatility", "regime"],
    },
    {
        "factor_id": "wq_style_volume_pressure_10_30",
        "name": "Volume Pressure Rank",
        "description": "Compares recent volume expansion against its own rolling baseline.",
        "formula_expression": "ts_rank(volume / mean(volume, 30), 10)",
        "factor_family": "volume",
        "strategy_family": StrategyFamily.GENERAL_OR_UNKNOWN,
        "evaluation_scope": FactorEvaluationScope.SINGLE_ASSET_TIME_SERIES,
        "implementation_status": FactorImplementationStatus.PORTABLE_OHLCV,
        "required_fields": ["volume"],
        "required_operators": ["mean", "ts_rank"],
        "lookback_windows": [10, 30],
        "baseline_roles": ["baseline_candidate", "volume_feature"],
        "crypto_compatibility_notes": ["Crypto exchange volume quality varies; pair this with data-quality flags."],
        "overfitting_warnings": ["Volume spikes are easy to overfit around exchange-specific microstructure."],
        "tags": ["ohlcv", "volume", "feature"],
    },
    {
        "factor_id": "wq_style_price_volume_corr_20",
        "name": "Price-Volume Correlation",
        "description": "Measures whether price changes and volume are moving together.",
        "formula_expression": "correlation(returns(close), volume, 20)",
        "factor_family": "price_volume_interaction",
        "strategy_family": StrategyFamily.CONTINUOUS_TREND_OR_MOMENTUM,
        "evaluation_scope": FactorEvaluationScope.SINGLE_ASSET_TIME_SERIES,
        "implementation_status": FactorImplementationStatus.PORTABLE_OHLCV,
        "required_fields": ["close", "volume"],
        "required_operators": ["returns", "correlation"],
        "lookback_windows": [20],
        "baseline_roles": ["baseline_candidate", "confirmation_feature"],
        "crypto_compatibility_notes": ["Can test whether trend strength needs volume confirmation."],
        "overfitting_warnings": _COMMON_OVERFITTING_WARNINGS,
        "tags": ["ohlcv", "correlation", "volume"],
    },
    {
        "factor_id": "wq_style_intraday_range_position",
        "name": "Close Location Value",
        "description": "Scores whether the close is near the high or low of the bar range.",
        "formula_expression": "(close - low) / max(high - low, epsilon)",
        "factor_family": "range_position",
        "strategy_family": StrategyFamily.FAILED_BREAKOUT_PUNISHMENT,
        "evaluation_scope": FactorEvaluationScope.SINGLE_ASSET_TIME_SERIES,
        "implementation_status": FactorImplementationStatus.PORTABLE_OHLCV,
        "required_fields": ["high", "low", "close"],
        "required_operators": ["safe_divide"],
        "lookback_windows": [1],
        "baseline_roles": ["baseline_candidate", "breakout_failure_feature"],
        "crypto_compatibility_notes": ["Useful as a bar-level proxy for rejection, but not a substitute for tick orderflow."],
        "overfitting_warnings": ["Single-bar rejection proxies must be stress-tested across fee/slippage assumptions."],
        "tags": ["ohlcv", "breakout", "range"],
    },
    {
        "factor_id": "wq_style_cross_sectional_momentum_20",
        "name": "Cross-Sectional Momentum Rank",
        "description": "Ranks symbols by recent return inside a multi-asset universe.",
        "formula_expression": "rank(close / delay(close, 20) - 1)",
        "factor_family": "cross_sectional_momentum",
        "strategy_family": StrategyFamily.CONTINUOUS_TREND_OR_MOMENTUM,
        "evaluation_scope": FactorEvaluationScope.CROSS_SECTIONAL_UNIVERSE,
        "implementation_status": FactorImplementationStatus.NEEDS_CROSS_SECTIONAL_UNIVERSE,
        "required_fields": ["symbol", "close"],
        "required_operators": ["delay", "rank"],
        "lookback_windows": [20],
        "baseline_roles": ["cross_sectional_baseline"],
        "crypto_compatibility_notes": ["Requires a stable crypto universe and survivorship-aware data."],
        "overfitting_warnings": ["Universe choice can dominate the apparent edge."],
        "tags": ["cross_sectional", "momentum", "universe"],
    },
    {
        "factor_id": "wq_style_cross_sectional_reversal_5",
        "name": "Cross-Sectional Reversal Rank",
        "description": "Ranks recent laggards higher inside a multi-asset universe.",
        "formula_expression": "-rank(close / delay(close, 5) - 1)",
        "factor_family": "cross_sectional_reversal",
        "strategy_family": StrategyFamily.VWAP_EXHAUSTION_REVERSION,
        "evaluation_scope": FactorEvaluationScope.CROSS_SECTIONAL_UNIVERSE,
        "implementation_status": FactorImplementationStatus.NEEDS_CROSS_SECTIONAL_UNIVERSE,
        "required_fields": ["symbol", "close"],
        "required_operators": ["delay", "rank"],
        "lookback_windows": [5],
        "baseline_roles": ["cross_sectional_baseline"],
        "crypto_compatibility_notes": ["Needs liquidity filters so tiny tokens do not dominate reversal results."],
        "overfitting_warnings": ["Cross-sectional reversal is very sensitive to listing date and liquidity filters."],
        "tags": ["cross_sectional", "reversal", "universe"],
    },
    {
        "factor_id": "wq_style_decay_momentum_10",
        "name": "Decay-Weighted Momentum",
        "description": "Applies linear decay to recent returns before ranking strength.",
        "formula_expression": "decay_linear(returns(close), 10)",
        "factor_family": "momentum",
        "strategy_family": StrategyFamily.CONTINUOUS_TREND_OR_MOMENTUM,
        "evaluation_scope": FactorEvaluationScope.SINGLE_ASSET_TIME_SERIES,
        "implementation_status": FactorImplementationStatus.PORTABLE_OHLCV,
        "required_fields": ["close"],
        "required_operators": ["returns", "decay_linear"],
        "lookback_windows": [10],
        "baseline_roles": ["baseline_candidate", "momentum_baseline"],
        "crypto_compatibility_notes": ["A good benchmark for testing whether complex trend logic adds value."],
        "overfitting_warnings": _COMMON_OVERFITTING_WARNINGS,
        "tags": ["ohlcv", "momentum", "decay"],
    },
    {
        "factor_id": "wq_style_liquidity_adjusted_reversal",
        "name": "Liquidity-Adjusted Reversal",
        "description": "Combines short-horizon reversal with recent volume availability.",
        "formula_expression": "-ts_rank(returns(close), 5) * ts_rank(volume, 20)",
        "factor_family": "liquidity_adjusted_reversal",
        "strategy_family": StrategyFamily.VWAP_EXHAUSTION_REVERSION,
        "evaluation_scope": FactorEvaluationScope.SINGLE_ASSET_TIME_SERIES,
        "implementation_status": FactorImplementationStatus.PORTABLE_OHLCV,
        "required_fields": ["close", "volume"],
        "required_operators": ["returns", "ts_rank"],
        "lookback_windows": [5, 20],
        "baseline_roles": ["baseline_candidate", "mean_reversion_baseline"],
        "crypto_compatibility_notes": ["Pairs naturally with low-liquidity disable rules."],
        "overfitting_warnings": ["Volume multiplication can amplify exchange artifacts."],
        "tags": ["ohlcv", "reversal", "liquidity"],
    },
    {
        "factor_id": "wq_style_beta_residual_momentum",
        "name": "Market-Residual Momentum",
        "description": "Scores residual return after removing broad-market movement.",
        "formula_expression": "returns(close, 20) - beta(symbol_returns, market_returns, 60) * market_returns",
        "factor_family": "market_residual",
        "strategy_family": StrategyFamily.CONTINUOUS_TREND_OR_MOMENTUM,
        "evaluation_scope": FactorEvaluationScope.PORTFOLIO_CONTEXT,
        "implementation_status": FactorImplementationStatus.NEEDS_CROSS_SECTIONAL_UNIVERSE,
        "required_fields": ["symbol", "close", "market_index_close"],
        "required_operators": ["returns", "beta"],
        "lookback_windows": [20, 60],
        "baseline_roles": ["portfolio_baseline", "regime_feature"],
        "crypto_compatibility_notes": ["Needs a BTC or total-market proxy and multi-symbol alignment."],
        "overfitting_warnings": ["Residualization can hide leverage to the chosen market proxy."],
        "tags": ["portfolio", "market_residual", "momentum"],
    },
    {
        "factor_id": "wq_style_funding_augmented_reversal",
        "name": "Funding-Augmented Reversal",
        "description": "QuantOdyssey extension: combines short reversal with funding pressure.",
        "formula_expression": "-ts_rank(returns(close), 5) * ts_rank(abs(funding_rate), 30)",
        "factor_family": "funding_reversal",
        "strategy_family": StrategyFamily.FUNDING_CROWDING_FADE,
        "evaluation_scope": FactorEvaluationScope.SINGLE_ASSET_TIME_SERIES,
        "implementation_status": FactorImplementationStatus.NEEDS_EXTRA_DATA,
        "data_sufficiency_level": DataSufficiencyLevel.L1_FUNDING_OI,
        "required_fields": ["close", "funding_rate"],
        "required_operators": ["returns", "abs", "ts_rank"],
        "lookback_windows": [5, 30],
        "baseline_roles": ["funding_baseline", "strategy_family_template"],
        "crypto_compatibility_notes": ["This is not a WorldQuant101 formula; it adapts the factor grammar to perpetual futures."],
        "overfitting_warnings": ["Must compare against funding-extreme-only and short-reversal-only baselines."],
        "tags": ["funding", "reversal", "perpetual"],
    },
]
